"""add user blocking

Revision ID: 0e3cd21fd7e7
Revises: 153bd29952c7
Create Date: 2026-01-22 20:32:16.654264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e3cd21fd7e7"
down_revision: Union[str, Sequence[str], None] = "153bd29952c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.add_column(
        "users",
        sa.Column("is_blocked", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "users", sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_users_is_blocked"), "users", ["is_blocked"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_blocked"), table_name="users")
    op.drop_column("users", "blocked_at")
    op.drop_column("users", "is_blocked")
    # ### end Alembic commands ###
