"""update task

Revision ID: 14c0f6bb7361
Revises: 1988ce16fe95
Create Date: 2026-01-20 22:57:19.858305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14c0f6bb7361"
down_revision: Union[str, Sequence[str], None] = "1988ce16fe95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "city_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "city_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
