"""update task

Revision ID: 1988ce16fe95
Revises: 3768b84bc2ed
Create Date: 2026-01-20 22:38:06.247974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1988ce16fe95"
down_revision: Union[str, Sequence[str], None] = "3768b84bc2ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("text", sa.Text(), nullable=False))
    op.add_column("tasks", sa.Column("example_text", sa.Text(), nullable=True))
    op.add_column("tasks", sa.Column("comment", sa.Text(), nullable=True))
    op.drop_column("tasks", "description")
    op.drop_column("tasks", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("title", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tasks",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "comment")
    op.drop_column("tasks", "example_text")
    op.drop_column("tasks", "text")
    # ### end Alembic commands ###
