"""add source to task

Revision ID: 2c132eb4c482
Revises: 12904b2db034
Create Date: 2026-02-07 14:27:32.591242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c132eb4c482"
down_revision: Union[str, Sequence[str], None] = "12904b2db034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("source", sa.String(length=32), nullable=True))
    op.alter_column(
        "users",
        "approved_by_admin_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "approved_by_admin_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("tasks", "source")
    # ### end Alembic commands ###
