"""task_assigments del

Revision ID: 3768b84bc2ed
Revises: 49b0698dcb25
Create Date: 2026-01-20 21:01:20.868272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3768b84bc2ed"
down_revision: Union[str, Sequence[str], None] = "49b0698dcb25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_assignments", "report_photo_file_id")
    op.drop_column("task_assignments", "report_account_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments",
        sa.Column(
            "report_account_name",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "task_assignments",
        sa.Column(
            "report_photo_file_id",
            sa.VARCHAR(length=512),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
