"""add user approval admin message

Revision ID: 38ce71380214
Revises: da3d4282c0ba
Create Date: 2026-01-23 20:10:22.646282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38ce71380214"
down_revision: Union[str, Sequence[str], None] = "da3d4282c0ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_approval_admin_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("admin_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_approval_admin_messages_admin_tg_id"),
        "user_approval_admin_messages",
        ["admin_tg_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_approval_admin_messages_user_id"),
        "user_approval_admin_messages",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_approval_admin_messages_user_id"),
        table_name="user_approval_admin_messages",
    )
    op.drop_index(
        op.f("ix_user_approval_admin_messages_admin_tg_id"),
        table_name="user_approval_admin_messages",
    )
    op.drop_table("user_approval_admin_messages")
    # ### end Alembic commands ###
