"""task_assigments update

Revision ID: 49b0698dcb25
Revises: e67eaac1301b
Create Date: 2026-01-20 16:06:49.855401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49b0698dcb25"
down_revision: Union[str, Sequence[str], None] = "e67eaac1301b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments",
        sa.Column("processed_by_admin_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "task_assignments",
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_task_assignments_processed_by_admin_id"),
        "task_assignments",
        ["processed_by_admin_id"],
        unique=False,
    )
    op.alter_column("tasks", "city_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "city_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index(
        op.f("ix_task_assignments_processed_by_admin_id"), table_name="task_assignments"
    )
    op.drop_column("task_assignments", "processed_at")
    op.drop_column("task_assignments", "processed_by_admin_id")
    # ### end Alembic commands ###
