"""message del task ass

Revision ID: 62e7ea91c882
Revises: 14c0f6bb7361
Create Date: 2026-01-21 17:27:53.787840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62e7ea91c882"
down_revision: Union[str, Sequence[str], None] = "14c0f6bb7361"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments", sa.Column("report_message_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_assignments", "report_message_id")
    # ### end Alembic commands ###
