"""add is_archived to task_assignments

Revision ID: 6e3f1fd3cbe9
Revises: 0e3cd21fd7e7
Create Date: 2026-01-22 21:49:36.258655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e3f1fd3cbe9"
down_revision: Union[str, Sequence[str], None] = "0e3cd21fd7e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments",
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(
        op.f("ix_task_assignments_is_archived"),
        "task_assignments",
        ["is_archived"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_task_assignments_is_archived"), table_name="task_assignments"
    )
    op.drop_column("task_assignments", "is_archived")
    # ### end Alembic commands ###
