"""admin edit message

Revision ID: 7b93140dbb45
Revises: 7eb5ac18b050
Create Date: 2026-01-21 17:53:18.759914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b93140dbb45"
down_revision: Union[str, Sequence[str], None] = "7eb5ac18b050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_assignment_admin_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("admin_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["task_assignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_assignment_admin_messages_admin_tg_id"),
        "task_assignment_admin_messages",
        ["admin_tg_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_admin_messages_assignment_id"),
        "task_assignment_admin_messages",
        ["assignment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_task_assignment_admin_messages_assignment_id"),
        table_name="task_assignment_admin_messages",
    )
    op.drop_index(
        op.f("ix_task_assignment_admin_messages_admin_tg_id"),
        table_name="task_assignment_admin_messages",
    )
    op.drop_table("task_assignment_admin_messages")
    # ### end Alembic commands ###
