"""admin edit message

Revision ID: 7eb5ac18b050
Revises: a8c12bbf4c72
Create Date: 2026-01-21 17:51:36.404515

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7eb5ac18b050"
down_revision: Union[str, Sequence[str], None] = "a8c12bbf4c72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
