"""alter type link

Revision ID: 8ece5af1973a
Revises: 6d2858652a98
Create Date: 2026-02-28 16:12:11.044030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ece5af1973a'
down_revision: Union[str, Sequence[str], None] = '6d2858652a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "link",
        existing_type=sa.String(length=512),
        type_=sa.Text(),
        existing_nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
        "tasks",
        "link",
        existing_type=sa.Text(),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
