"""add index

Revision ID: 97fdd73f0f1a
Revises: 3df9e8b8b645
Create Date: 2026-02-07 16:28:52.864022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97fdd73f0f1a"
down_revision: Union[str, Sequence[str], None] = "3df9e8b8b645"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ux_task_assignments_task_active",
        "task_assignments",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("is_archived = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_task_assignments_task_active",
        table_name="task_assignments",
        postgresql_where=sa.text("is_archived = false"),
    )
    # ### end Alembic commands ###
