"""admin edit message

Revision ID: a8c12bbf4c72
Revises: 62e7ea91c882
Create Date: 2026-01-21 17:42:43.936748

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a8c12bbf4c72"
down_revision: Union[str, Sequence[str], None] = "62e7ea91c882"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
