"""add user approved

Revision ID: da3d4282c0ba
Revises: 6e3f1fd3cbe9
Create Date: 2026-01-23 19:58:20.557690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da3d4282c0ba"
down_revision: Union[str, Sequence[str], None] = "6e3f1fd3cbe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "approval_status",
            sa.String(length=16),
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("approval_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("approved_by_admin_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("approval_comment", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_users_approval_status"), "users", ["approval_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_approval_status"), table_name="users")
    op.drop_column("users", "approval_comment")
    op.drop_column("users", "approved_by_admin_id")
    op.drop_column("users", "approval_at")
    op.drop_column("users", "approval_status")
    # ### end Alembic commands ###
