"""task update

Revision ID: e67eaac1301b
Revises: a3ff56b24063
Create Date: 2026-01-19 19:12:56.783706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e67eaac1301b"
down_revision: Union[str, Sequence[str], None] = "a3ff56b24063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments",
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "task_assignments",
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "task_assignments",
        sa.Column("report_account_name", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "task_assignments",
        sa.Column("report_photo_file_id", sa.String(length=512), nullable=True),
    )
    op.alter_column(
        "task_assignments",
        "status",
        existing_type=sa.VARCHAR(length=24),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_task_assignment_task_id"), "task_assignments", type_="unique"
    )
    op.create_index(
        op.f("ix_task_assignments_status"), "task_assignments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_task_assignments_task_id"),
        "task_assignments",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignments_user_id"),
        "task_assignments",
        ["user_id"],
        unique=False,
    )
    op.drop_column("task_assignments", "updated_at")
    op.drop_column("tasks", "city_id")
    op.add_column(
        "tasks",
        sa.Column("city_id", sa.UUID(), sa.ForeignKey("cities.id"), nullable=True),
    )

    op.create_foreign_key(None, "tasks", "cities", ["city_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.alter_column(
        "tasks", "city_id", existing_type=sa.UUID(), type_=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "task_assignments",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_task_assignments_user_id"), table_name="task_assignments")
    op.drop_index(op.f("ix_task_assignments_task_id"), table_name="task_assignments")
    op.drop_index(op.f("ix_task_assignments_status"), table_name="task_assignments")
    op.create_unique_constraint(
        op.f("uq_task_assignment_task_id"),
        "task_assignments",
        ["task_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "task_assignments",
        "status",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=24),
        existing_nullable=False,
    )
    op.drop_column("task_assignments", "report_photo_file_id")
    op.drop_column("task_assignments", "report_account_name")
    op.drop_column("task_assignments", "approved_at")
    op.drop_column("task_assignments", "submitted_at")
    # ### end Alembic commands ###
